settings:
  title: 'Nui Status Page'
  url: 'https://status.ngxson.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: nuichatbot
    name: Nui Chatbot
    description: 'Nui Chatbot server'
    url: 'https://nuichatbot.herokuapp.com/test/read'
    method: GET
    expectStatus: 200 
    followRedirect: false
    linkable: false

  - id: nui-wp-net
    name: Nui WordPress Network
    description: 'Nui WordPress Network main site'
    url: 'https://wp-network.ngxson.com/'
    method: GET
    expectStatus: 200 
    followRedirect: false
    linkable: true

  - id: cnh-spl
    name: CNH Spotlight
    description: 'Trang tin tức của học sinh trường THPT chuyên Nguyễn Huệ được thành lập và quản lý bới CLB CNH Spotlight'
    url: 'https://chuyennguyenhue.com/'
    method: GET
    expectStatus: 200 
    followRedirect: false
    linkable: true

  - id: uevam
    name: UEVAM
    description: 'Hội sinh viên Việt Nam tại Aix-Marseille'
    url: 'https://uevam.fr/'
    method: GET
    expectStatus: 200 
    followRedirect: false
    linkable: true

  - id: voge
    name: VOGE
    description: 'Tổ chức thúc đẩy bình đẳng với Việt Nam'
    url: 'https://voge.vn/'
    method: GET
    expectStatus: 200 
    followRedirect: false
    linkable: true

  - id: donghanh-net
    name: VOGE
    description: 'Quỹ học bổng Đồng Hành'
    url: 'https://donghanh.net/'
    method: GET
    expectStatus: 200 
    followRedirect: false
    linkable: true

  - id: tonghopevent
    name: tonghopduancuocthi.web.app
    description: 'Tổng hợp các dự án và cuộc thi dành cho học sinh, sinh viên'
    url: 'https://tonghopduancuocthi.web.app/'
    method: GET
    expectStatus: 200 
    followRedirect: false
    linkable: true
